ci clean up.

diff --git a/.github/workflows/selfdrive_tests.yaml b/.github/workflows/selfdrive_tests.yaml
--- a/.github/workflows/selfdrive_tests.yaml
+++ b/.github/workflows/selfdrive_tests.yaml
@@ -146,40 +146,40 @@ jobs:
   #      done
   #      comm -13 <(echo "$EXISTING_CELLAR") <(echo "$new_cellar") | tee ~/github_brew_cache_entries.txt
 
-  build_webcam:
-    name: build webcam
-    runs-on: ubuntu-20.04
-    timeout-minutes: 90
-    env:
-      IMAGE_NAME: openpilotwebcamci
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        submodules: true
-    - name: Cache scons
-      id: scons-cache
+  #build_webcam:
+  #  name: build webcam
+  #  runs-on: ubuntu-20.04
+  #  timeout-minutes: 90
+  #  env:
+  #    IMAGE_NAME: openpilotwebcamci
+  #  steps:
+  #  - uses: actions/checkout@v3
+  #    with:
+  #      submodules: true
+  #  - name: Cache scons
+  #    id: scons-cache
       # TODO: Change the version to the released version when https://github.com/actions/cache/pull/489 (or 571) is merged.
-      uses: actions/cache@03e00da99d75a2204924908e1cca7902cafce66b
-      env:
-        CACHE_SKIP_SAVE: true
-      with:
-        path: /tmp/scons_cache
-        key: scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
-        restore-keys: |
-          scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
-          scons-
-    - name: Build Docker image
-      run: |
-        eval "$BUILD"
-        docker pull $DOCKER_REGISTRY/$IMAGE_NAME:latest || true
-        docker build --cache-from $DOCKER_REGISTRY/$IMAGE_NAME:latest -t $DOCKER_REGISTRY/$IMAGE_NAME:latest -f tools/webcam/Dockerfile .
-    - name: Build openpilot
-      run: docker run --shm-size 1G --rm -v $PWD:/tmp/openpilot -e PYTHONPATH=/tmp/openpilot $DOCKER_REGISTRY/$IMAGE_NAME /bin/sh -c "cd /tmp/openpilot && USE_WEBCAM=1 scons -j$(nproc)"
-    - name: Push to container registry
-      if: github.ref == 'refs/heads/master' && github.repository == 'commaai/openpilot'
-      run: |
-        $DOCKER_LOGIN
-        docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
+  #    uses: actions/cache@03e00da99d75a2204924908e1cca7902cafce66b
+  #    env:
+  #      CACHE_SKIP_SAVE: true
+  #    with:
+  #      path: /tmp/scons_cache
+  #      key: scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
+  #      restore-keys: |
+  #        scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
+  #        scons-
+  #  - name: Build Docker image
+  #    run: |
+  #      eval "$BUILD"
+  #      docker pull $DOCKER_REGISTRY/$IMAGE_NAME:latest || true
+  #      docker build --cache-from $DOCKER_REGISTRY/$IMAGE_NAME:latest -t $DOCKER_REGISTRY/$IMAGE_NAME:latest -f tools/webcam/Dockerfile .
+  #  - name: Build openpilot
+  #    run: docker run --shm-size 1G --rm -v $PWD:/tmp/openpilot -e PYTHONPATH=/tmp/openpilot $DOCKER_REGISTRY/$IMAGE_NAME /bin/sh -c "cd /tmp/openpilot && USE_WEBCAM=1 scons -j$(nproc)"
+  #  - name: Push to container registry
+  #    if: github.ref == 'refs/heads/master' && github.repository == 'commaai/openpilot'
+  #    run: |
+  #      $DOCKER_LOGIN
+  #      docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
 
   docker_push:
     name: docker push
@@ -302,55 +302,55 @@ jobs:
     - name: "Upload coverage to Codecov"
       uses: codecov/codecov-action@v2
 
-  process_replay:
-    name: process replay
-    runs-on: ubuntu-20.04
-    timeout-minutes: 50
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        submodules: true
-    - name: Cache dependencies
-      id: dependency-cache
-      uses: actions/cache@v2
-      with:
-        path: /tmp/comma_download_cache
-        key: ${{ hashFiles('.github/workflows/selfdrive_tests.yaml', 'selfdrive/test/process_replay/test_processes.py') }}
-    - name: Cache scons
-      id: scons-cache
+  #process_replay:
+  #  name: process replay
+  #  runs-on: ubuntu-20.04
+  #  timeout-minutes: 50
+  #  steps:
+  #  - uses: actions/checkout@v3
+  #    with:
+  #      submodules: true
+  #  - name: Cache dependencies
+  #    id: dependency-cache
+  #    uses: actions/cache@v2
+  #    with:
+  #      path: /tmp/comma_download_cache
+  #      key: ${{ hashFiles('.github/workflows/selfdrive_tests.yaml', 'selfdrive/test/process_replay/test_processes.py') }}
+  #  - name: Cache scons
+  #    id: scons-cache
       # TODO: Change the version to the released version when https://github.com/actions/cache/pull/489 (or 571) is merged.
-      uses: actions/cache@03e00da99d75a2204924908e1cca7902cafce66b
-      env:
-        CACHE_SKIP_SAVE: true
-      with:
-        path: /tmp/scons_cache
-        key: scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
-        restore-keys: |
-          scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
-          scons-
-    - name: Build Docker image
-      run: eval "$BUILD"
-    - name: Run replay
-      run: |
-        ${{ env.RUN }} "scons -j$(nproc) && \
-                        FILEREADER_CACHE=1 CI=1 coverage run selfdrive/test/process_replay/test_processes.py -j$(nproc) && \
-                        coverage xml"
-    - name: Print diff
-      if: always()
-      run: cat selfdrive/test/process_replay/diff.txt
-    - uses: actions/upload-artifact@v2
-      if: always()
-      continue-on-error: true
-      with:
-        name: process_replay_diff.txt
-        path: selfdrive/test/process_replay/diff.txt
-    - name: Upload reference logs
-      if: ${{ failure() && github.event_name == 'pull_request' && github.repository == 'commaai/openpilot' && env.AZURE_TOKEN != '' }}
-      run: |
-        ${{ env.RUN }} "scons -j$(nproc) && \
-                        CI=1 AZURE_TOKEN='$AZURE_TOKEN' python selfdrive/test/process_replay/test_processes.py -j$(nproc) --upload-only"
-    - name: "Upload coverage to Codecov"
-      uses: codecov/codecov-action@v2
+  #    uses: actions/cache@03e00da99d75a2204924908e1cca7902cafce66b
+  #    env:
+  #      CACHE_SKIP_SAVE: true
+  #    with:
+  #      path: /tmp/scons_cache
+  #      key: scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
+  #      restore-keys: |
+  #        scons-${{ hashFiles('.github/workflows/selfdrive_tests.yaml') }}-
+  #        scons-
+  #  - name: Build Docker image
+  #    run: eval "$BUILD"
+  #  - name: Run replay
+  #    run: |
+  #      ${{ env.RUN }} "scons -j$(nproc) && \
+  #                      FILEREADER_CACHE=1 CI=1 coverage run selfdrive/test/process_replay/test_processes.py -j$(nproc) && \
+  #                      coverage xml"
+  #  - name: Print diff
+  #    if: always()
+  #    run: cat selfdrive/test/process_replay/diff.txt
+  #  - uses: actions/upload-artifact@v2
+  #    if: always()
+  #    continue-on-error: true
+  #    with:
+  #      name: process_replay_diff.txt
+  #      path: selfdrive/test/process_replay/diff.txt
+  #  - name: Upload reference logs
+  #    if: ${{ failure() && github.event_name == 'pull_request' && github.repository == 'commaai/openpilot' && env.AZURE_TOKEN != '' }}
+  #    run: |
+  #      ${{ env.RUN }} "scons -j$(nproc) && \
+  #                      CI=1 AZURE_TOKEN='$AZURE_TOKEN' python selfdrive/test/process_replay/test_processes.py -j$(nproc) --upload-only"
+  #  - name: "Upload coverage to Codecov"
+  #    uses: codecov/codecov-action@v2
 
   test_longitudinal:
     name: longitudinal
@@ -434,21 +434,21 @@ jobs:
     - name: "Upload coverage to Codecov"
       uses: codecov/codecov-action@v2
 
-  docs:
-    name: build docs
-    runs-on: ubuntu-20.04
-    timeout-minutes: 50
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        submodules: true
-    - name: Build docker container
-      run: |
-        docker pull $DOCKER_REGISTRY/$BASE_IMAGE:latest || true
-        docker pull $DOCKER_REGISTRY/openpilot-docs:latest || true
-        DOCKER_BUILDKIT=1 docker build --cache-from $DOCKER_REGISTRY/openpilot-docs:latest -t $DOCKER_REGISTRY/openpilot-docs:latest -f docs/docker/Dockerfile .
-    - name: Push docker container
-      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'commaai/openpilot'
-      run: |
-        $DOCKER_LOGIN
-        docker push $DOCKER_REGISTRY/openpilot-docs:latest
+  #docs:
+  #  name: build docs
+  #  runs-on: ubuntu-20.04
+  #  timeout-minutes: 50
+  #  steps:
+  #  - uses: actions/checkout@v3
+  #    with:
+  #      submodules: true
+  #  - name: Build docker container
+  #    run: |
+  #      docker pull $DOCKER_REGISTRY/$BASE_IMAGE:latest || true
+  #      docker pull $DOCKER_REGISTRY/openpilot-docs:latest || true
+  #      DOCKER_BUILDKIT=1 docker build --cache-from $DOCKER_REGISTRY/openpilot-docs:latest -t $DOCKER_REGISTRY/openpilot-docs:latest -f docs/docker/Dockerfile .
+  #  - name: Push docker container
+  #    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'commaai/openpilot'
+  #    run: |
+  #      $DOCKER_LOGIN
+  #      docker push $DOCKER_REGISTRY/openpilot-docs:latest
